
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CBN
 */
public class formulario_SeguroDeVida extends javax.swing.JFrame {
 

    /**
     * Creates new form formulario_SeguroDeVida
     */
    SeguroDeVida calcularSeguro = new SeguroDeVida();
    boolean siFumador=false, siAlcoholico=false, siDrogadicto=false, siCardiaco=false;
    long valorBase=0;
    public formulario_SeguroDeVida() {
        initComponents();
        txtValorBase.setText("");
        lbresultado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgfumadores = new javax.swing.ButtonGroup();
        rgalcoholico = new javax.swing.ButtonGroup();
        rgsustancias = new javax.swing.ButtonGroup();
        rgcardiacos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtValorBase = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbfumadorsi = new javax.swing.JRadioButton();
        rbfumadorno = new javax.swing.JRadioButton();
        rbalcoholicosi = new javax.swing.JRadioButton();
        rbalcoholicono = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbsustanciasi = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbsustanciano = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbantecedentesi = new javax.swing.JRadioButton();
        rbantecedentesno = new javax.swing.JRadioButton();
        chkaceptar = new javax.swing.JCheckBox();
        btncalcular = new javax.swing.JButton();
        lbresultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese el valor base");

        jLabel2.setText("Es usted fumador activo?");

        rgfumadores.add(rbfumadorsi);
        rbfumadorsi.setText("Si");

        rgfumadores.add(rbfumadorno);
        rbfumadorno.setText("No");

        rgalcoholico.add(rbalcoholicosi);
        rbalcoholicosi.setText("Si");

        rgalcoholico.add(rbalcoholicono);
        rbalcoholicono.setText("No");

        jLabel3.setText("Es usted alcoholico");

        rgsustancias.add(rbsustanciasi);
        rbsustanciasi.setText("Si");

        jLabel4.setText("Consume sustancias alcogenas");

        rgsustancias.add(rbsustanciano);
        rbsustanciano.setText("No");

        jLabel5.setText("Tiene antecedentes cardiacos");

        rgcardiacos.add(rbantecedentesi);
        rbantecedentesi.setText("Si");

        rgcardiacos.add(rbantecedentesno);
        rbantecedentesno.setText("No");

        chkaceptar.setText("Acepto los terminos y condiciones");
        chkaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkaceptarActionPerformed(evt);
            }
        });

        btncalcular.setText("Calcular seguro de vida");
        btncalcular.setEnabled(false);
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        lbresultado.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbfumadorsi)
                            .addComponent(rbfumadorno)
                            .addComponent(jLabel2))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btncalcular)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbalcoholicono)
                                    .addComponent(rbalcoholicosi))
                                .addGap(161, 161, 161)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbsustanciasi)
                                    .addComponent(rbsustanciano))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(txtValorBase, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbresultado)
                            .addComponent(chkaceptar)
                            .addComponent(rbantecedentesno)
                            .addComponent(rbantecedentesi)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValorBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbfumadorsi)
                    .addComponent(rbalcoholicosi)
                    .addComponent(rbsustanciasi))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbfumadorno)
                    .addComponent(rbalcoholicono)
                    .addComponent(rbsustanciano))
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(rbantecedentesi)
                .addGap(18, 18, 18)
                .addComponent(rbantecedentesno)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkaceptar)
                    .addComponent(btncalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lbresultado)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkaceptarActionPerformed
        // TODO add your handling code here:
        if(chkaceptar.isSelected()){
        btncalcular.setEnabled(true);
        }else{
        btncalcular.setEnabled(false);
        }
        
    }//GEN-LAST:event_chkaceptarActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
       try{
           calcularSeguro();
           
       }catch (Exception e){
           JOptionPane.showMessageDialog(null,"Faltan campos por diligenciar ", "Error ", JOptionPane.ERROR_MESSAGE);
       }
       
    }//GEN-LAST:event_btncalcularActionPerformed
     private void calcularSeguro(){
         valorBase=Long.parseLong(txtValorBase.getText());
         if(rbfumadorsi.isSelected()){
             siFumador=true;
             
         }else{
             siFumador=false;
         }if (rbalcoholicosi.isSelected()){
             siAlcoholico=true;
             
         }else{
             siAlcoholico=false;
         } if(rbsustanciasi.isSelected()){
             siDrogadicto=true;
         }else{
             siDrogadicto=false;
             
         }if (rbantecedentesi.isSelected()){
             siCardiaco=true;
         }else{
             siCardiaco=false;
         }
         formulario2 formulario22 = new formulario2(Long.toString(calcularSeguro.Calcular(valorBase,siFumador,siAlcoholico,siDrogadicto,siCardiaco)));
         formulario22.setVisible(true);
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario_SeguroDeVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario_SeguroDeVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario_SeguroDeVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario_SeguroDeVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario_SeguroDeVida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JCheckBox chkaceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbresultado;
    private javax.swing.JRadioButton rbalcoholicono;
    private javax.swing.JRadioButton rbalcoholicosi;
    private javax.swing.JRadioButton rbantecedentesi;
    private javax.swing.JRadioButton rbantecedentesno;
    private javax.swing.JRadioButton rbfumadorno;
    private javax.swing.JRadioButton rbfumadorsi;
    private javax.swing.JRadioButton rbsustanciano;
    private javax.swing.JRadioButton rbsustanciasi;
    private javax.swing.ButtonGroup rgalcoholico;
    private javax.swing.ButtonGroup rgcardiacos;
    private javax.swing.ButtonGroup rgfumadores;
    private javax.swing.ButtonGroup rgsustancias;
    private javax.swing.JTextField txtValorBase;
    // End of variables declaration//GEN-END:variables
}
